repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
        files: \.(py)$
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.1  # select the tag or revision you want, or run `pre-commit autoupdate`
    hooks:
    -   id: autopep8
        args: ['--in-place', '--aggressive', '--aggressive']

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: [--line-length=72]
