#!/usr/bin/env bash
# configures nginx to redirect /redirect_me to another page

printf %s "server {
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" >> /var/www/sites-available/default
