#!/usr/bin/env bash
# configures nginx to redirect /redirect_me to another page
apt-get update
apt-get upgrade -y
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
printf %s "server {
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" >> /var/www/sites-available/default
