#!/usr/bin/env bash
# This script installs nginx and configures it to add a custom header containing server hostname.

# Install Nginx if it's not installed
if ! command -v nginx &> /dev/null; then
    sudo apt-get update
    sudo apt-get install -y nginx
else
    echo "Nginx is already installed."
fi

service nginx start

# Create a simple HTML file
mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World" > /var/www/html/index.html

# Create a custom 404 page
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Define a custom header configuration
NGINX_CONFIG="/etc/nginx/sites-available/default"


# Write the custom header configuration
printf %s "server {
    add_header X-Served-By $HOSTNAME;
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.
        try_files \$uri \$uri/ =404;
    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location /404 {
        root /var/www/html;
        internal;
    }
}" | sudo tee "$NGINX_CONFIG"

# sed "/server {/a\    add_header X-Served-By $HOSTNAME;" "$NGINX_CONFIG" | sudo tee "$NGINX_CONFIG"

# Reload Nginx to apply the changes
sudo nginx -s reload
# service nginx restart
