#!/usr/bin/env bash

# This script installs nginx and configures it to add a custom header containing server hostname.

# Install Nginx if it's not installed
if ! command -v nginx &> /dev/null; then
    sudo apt-get update
    sudo apt-get install -y nginx
fi

# Define a custom header configuration
NGINX_CONFIG="/etc/nginx/sites-available/default"

# Get the server's hostname
HOSTNAME=$(hostname)

# Write the custom header configuration
sed "server {/a\    add_header X-Served-By $HOSTNAME;" | sudo tee $NGINX_CONFIG

# Reload Nginx to apply the changes
sudo nginx -s reload
# service nginx restart
