#!/usr/bin/env bash
# makes nginx listen on port 80
sudo apt-get install nginx -y
service nginx start
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    server_name _;
    location / {
        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.
        try_files \$uri \$uri/ =404;
    }
}
" | sudo tee /etc/nginx/sites-available/default
service nginx restart
