#!/usr/bin/env bash
# makes nginx listen on port 80
sed -i 's/listen 80 default_server;;/listen 80;/g' /etc/nginx/sites-enabled/default
sed -i 's/listen [::]:80 default_server;/listen [::]:80;/g' /etc/nginx/sites-enabled/default
service nginx restart
pkill -9 nginx
