#!/usr/bin/env bash
# script that displays the PID, along with the process name, of processes whose name contain the word bash

# find pids with names containing bash
pids=$(pgrep -f bash)

# if no process is found do nothing
if [ -n "$pids" ]; then
    for pid in $pids; do
        echo "$pid bash"
    done
fi
