#!/usr/bin/env bash
# script that stops 4-to_infinity_and_beyond process

process_name="4-to_infinity_and_beyond"
pid=$(pgrep -f "$process_name")
# if pid exists kill it
if [ -n "$pid" ]; then
    kill -2 "$pid"
    # echo "$pid" | xargs kill -2
fi
