#!/usr/bin/env bash
# script that displays To infinity and beyond indefinitely

# print I am invincible!!! when killed using SIGTERM signal
handle_sigterm(){
    echo "I am invincible!!!"
}

trap 'handle_sigterm' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
