#!/usr/bin/env bash
# displays the content of the file /etc/passwd

file_path="/etc/passwd"

# Check if the file exists
if [ -e "$file_path" ]; then
    # Read the file line by line
    while IFS= read -r line; do
        # echo "$line"
        # You can add your code to process each line here
        echo "$line" | cut -d ":" -f 1,3,6
    done < "$file_path"
else
    echo "The file $file_path does not exist."
fi
