#!/usr/bin/env bash
# prints "Best School" 10 times using while loop

hours=0

while [ $hours -le 12 ] ; do
    echo "Hour: $hours"

    mins=1
    while [ $mins -le 59 ]; do
        echo $mins
        mins=$((mins+1))
    done

    hours=$((hours+1))
done
