#!/usr/bin/env bash
#   gives you information about the school file.

filename="school"

if [ -e "$filename" ]; then
    echo "school file exists"

    if [ ! -s "$filename" ]; then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi

    if [ -e "$filename" ]; then
        echo "school file is empty"
    fi

else
    echo "school file does not exist"
fi
