#!/usr/bin/env bash
# A script that blocks all incoming traffic but allows except SSH, HTTPS and HTTP

# Install ufw if not installed
sudo apt-get update && sudo apt-get install ufw -y

# Deny all incoming traffic
sudo ufw default deny incoming

# Allow SSH, HTTPS and HTTP
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Enable ufw
sudo ufw enable
