#!/usr/bin/env bash
# script that changes hosts configuration on Ubuntu

config='127.0.0.2   localhost
8.8.8.8    facebook.com
'
cp /etc/hosts ~/hosts.new
echo "$config" > ~/hosts.new

cp -f ~/hosts.new /etc/hosts
